feat: add main service
mikhaeltatischev/java-explore-with-me pull request #8
Opened 2023-08-14 21:26 UTC by mikhaeltatischev

2023-08-15 20:57 UTC, sergeymamonov requested changes
Везде, где можно заменить самописный конструктор аннотацией Ломбок, лучше воспользоваться аннотацией.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +        PageRequest pageRequest = PageRequest.of(from / size, size);
size не провалидирован, может привести к делению на ноль.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository repository) {
Лучше воспользоваться аннотацией Ломбок, чем писать конструктор руками. Проверить по всему коду.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/AdminController.java
> +public class AdminController {
Решение не очень, в одном контроллере сосредотачивать эндпоинты разных сущностей. API часто разрастается, и рано или поздно решение придется переделать, поэтому лучше сразу сделать эндпоинты по сущностям. Но не настаиваю на этом решении.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/category/dto/CategoryDto.java
> +    private Long id;
Классы dto можно сделать иммутабельными.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/common/GlobalExceptionHandler.java
> +    public ApiError handleBadRequestStatusException(final BadRequestStatusException e) {
А где по коду кидается такая ошибка?

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +        // Как избежать такого в методах? Сидел целый день возился с запросами в репозитории, чтобы нулевые значения в параметры передавать
Если я правильно понял вопрос, то как избежать кучи if (parameters.getText() != null и передавать в запрос только не нулевые параметры?

Я бы сделал так: скорее всего один запрос (или несколько, зависит от бизнес логики). Запрос принимал бы объект query (а не отдельные параметры, как сейчас). И в самом запросе уже проверял, если конкретное поле в query не нулл, то добавляю его в фильтр. Для этого хорошо подходит queryDsl. Как сейчас сделано, когда запрос в форме строки, тоже можно попробовать собирать строку в зависимости от не нулевых параметров. Минус такого решения, что на этапе компиляции не проверится верно ли собран запрос, и можно получить ошибку в рантайме.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/resources/schema.sql
> +    annotation VARCHAR                                                         NOT NULL,
Размер лучше ограничить.

2023-08-15 20:57 UTC, sergeymamonov commented on ewm-service/src/main/resources/schema.sql
> +    description VARCHAR                                                        NOT NULL,
Аналогично.

2023-08-16 09:18 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +        PageRequest pageRequest = PageRequest.of(from / size, size);
Поставил аннотацию min (1) в контроллере

2023-08-16 09:22 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +    public UserServiceImpl(UserRepository repository) {
Поправил

2023-08-16 09:23 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/AdminController.java
> +public class AdminController {
Отталкивался от пути "/admin", но послушаю совета, самому показалось странным так делать

2023-08-16 09:58 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/category/dto/CategoryDto.java
> +    private Long id;
Поправил

2023-08-16 10:02 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/common/GlobalExceptionHandler.java
> +    public ApiError handleBadRequestStatusException(final BadRequestStatusException e) {
Поправил

2023-08-16 10:09 UTC, mikhaeltatischev commented on ewm-service/src/main/resources/schema.sql
> +    annotation VARCHAR                                                         NOT NULL,
Поправил

2023-08-16 10:09 UTC, mikhaeltatischev commented on ewm-service/src/main/resources/schema.sql
> +    description VARCHAR                                                        NOT NULL,
Поправил

2023-08-16 10:46 UTC, mikhaeltatischev commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +        // Как избежать такого в методах? Сидел целый день возился с запросами в репозитории, чтобы нулевые значения в параметры передавать
Решил пока так оставить, что-то всё ломаться начало, при подключении queryDsl, боюсь это надолго

2023-08-16 20:06 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/controller/EventController.java
> +                                          @RequestParam(defaultValue = "0", name = "from") int from,
А если клиент укажет from = -1, что будет?

2023-08-16 20:06 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +        PageRequest pageRequest = PageRequest.of(from / size, size);
А from провалидировать?

2023-08-16 20:07 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/category/dto/CategoryDto.java
> +    private Long id;
Посмотрите, что значит иммутабельный класс. В случае с dto поля можно тоже добавить модификатор final.

2023-08-16 20:12 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +        // Как избежать такого в методах? Сидел целый день возился с запросами в репозитории, чтобы нулевые значения в параметры передавать
Если есть время, то лучше изменить. На queryDsl переходить не обязательно, а вот запрос, чтобы он включал только не null параметры можно попробовать сделать. Вариант, собирать запрос, как строку если параметр не null, то добавить к запросу еще строку с условием. Можно обратиться к наставнику, может подскажет еще какие-то решения для такого случая.

2023-08-16 20:13 UTC, sergeymamonov approved these changes

2023-08-17 10:38 UTC, closed without merging